### ISSUE TITLE
closeout banner

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/lesson-style#19]
My [fork of the basic-r-lesson](https://itcarroll.github.io/basic-R-lesson/) has a banner highlighting end-of-maintenance.

A few suggested topics for comment:
- What's the date?
- It would take a lot more effort to splash this banner on archived lessons, because there is no mechanism to rebuild them (quite intentionally). The same logic would suggest archived lessons do not need the banner.
- Process:
  - I'll submit a PR to this repo, and then use the handouts Makefile to apply the update to every lesson in the [cyberhelp.sesync.org tag](https://github.com/SESYNC-ci/handouts/blob/master/lessons.yml#L90) directly (without individual PRs).
  - I'll submit a PR to sesync-ci.github.io adding the same banner to the FAQ, Quickstart, and Blog articles.

**Comment by reblake** [comment]
Banner in your forked lesson looks good.  Certainly eye-catching! 

 - Not yet sure the exact date that should be used.  It would be sometime after Dec 2022. 
 - Not sure what you mean with this point.  We'd want the banner on all the lessons listed here:  https://cyberhelp.sesync.org/lesson/
 - the linked tag list needs to be updated; it currently doesn't reflect the ~30 lessons listed here: https://cyberhelp.sesync.org/lesson/

**Comment by itcarroll** [comment]
- I'll just say Dec 2022 with no day.
- I mean the (time-stamped) lessons linked from old syllabi listed at http://sesync.org/for-you/cyberinfrastructure/institutes.
- ~~Will do.~~ Done.

Is there going to be a 2022 summer institute?

**Comment by reblake** [comment]
- Ok
- Didn't know that page existed.  Don't know if it will be migrated to new Drupal 9 website.  If it is, and someone clicks on an old syllabus, then presumably they understand the material might be out of date.  I wouldn't worry about this.
- TY!

Right now there are no plans for a 2022 summer institute.

**Comment by qdread** [comment]
Agreed, the banner looks nice! Are you going to put it on the lessons effective now or only closer to the date?

**Comment by reblake** [comment]
Let's not activate the banner just yet.  We still have some funded active teams, and we don't want to archive things until they are done.

**Comment by itcarroll** [comment]
I'll create the PR then, and can delay merging until you advise.

**Comment by itcarroll** [comment]
I see "cyberhelp.sesync.org" is gone :(
